config: &config
  - .github/**
  - pnpm-workspace.yaml
  - '*.config.ts'
  - '**.json5?'
  - '**.md'
  - '**.yaml'
  - '**.yml'
dist-changed:
  - added|modified: 'dist/**'
docs-changed: &docs-changed
  - docs/**
src-changed: &src-changed
  - .github/workflows/**
  - docker/**
  - '**/src/**'
  - action.yaml
  - '**/package.json'
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - '**/tsconfig.json'
renovate-changed:
  - .github/workflows/renovate.yaml
  - .github/renovate.json5
  - docker/entrypoint.sh
  - action.yaml
should-check:
  - added|modified: *config
  - added|modified: *docs-changed
  - added|modified: *src-changed
