config: &config
  - .github/**
  - .tool-versions
  - .npmrc
  - eslint.config.js
  - '**.json5?'
  - '**.md'
  - '**.yaml'
  - '**.yml'
dist-changed:
  - added|modified: 'dist/**'
src-changed: &src-changed
  - .github/workflows/**
  - .tool-versions
  - .npmrc
  - __tests__/**
  - docker/**
  - src/**
  - action.yaml
  - package.json
  - pnpm-lock.yaml
  - tsconfig.json
renovate-changed:
  - .github/workflows/renovate.yaml
  - .github/renovate.json5
  - action.yaml
should-check:
  - added|modified: *config
  - added|modified: *src-changed
