---
config:
  MD013: false
  MD033:
    allowed_elements: [a, h3, img, p]
  MD041: false

globs:
  - '**/*.md'
  - '!.cursorrules'
  - '!**/node_modules'
  - '!.cursor/rules/**'
  - '!.specstory/**'
  - '!.ai/**'
