---
arrowParens: avoid
bracketSpacing: false
jsxSingleQuote: true
overrides:
  - files:
      - '.vscode/**/*.json'
    options:
      tabWidth: 4
printWidth: 120
semi: false
singleQuote: true
tabWidth: 2
