---
name: Renovate Action
description: Self-hosted Renovate GitHub Action
author: bfra.me

inputs:
  autodiscover:
    description: Autodiscover all repositories.
    required: false
    default: 'false'
  branch:
    description: Run Renovate on this branch.
    required: false
  cache:
    description: Enable the Renovate cache.
    required: false
    default: 'false'
  dry_run:
    description: Perform a dry run by logging messages instead of creating/updating/deleting branches and PRs.
    required: false
    default: 'false'
  log_level:
    description: Set the log level.
    required: false
    default: 'info'
  print_config:
    description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
    required: false
    default: 'false'
  renovate_app_id:
    description: The ID of the GitHub App that will be used to run Renovate.
    required: true
  renovate_app_pem:
    description: The private key of the GitHub App that will be used to run Renovate.
    required: true
  renovate_app_slug:
    description: The slug of the GitHub app to use for authentication.
    required: true

outputs:
  docker-image:
    description: The name of the Renovate Docker image
    value: ${{ steps.configure.outputs.docker-image }}
  renovate-version:
    description: The Renovate version
    value: ${{ steps.configure.outputs.renovate-version }}

runs:
  steps:
    - name: Configure
      id: configure
      env:
        RENOVATE_VERSION: 37.419.0 # renovate: datasource=docker depName=renovate packageName=ghcr.io/renovatebot/renovate
        autodiscover: ${{ inputs.autodiscover != '' && inputs.autodiscover || 'false' }}
        dry_run: ${{ inputs.dry_run != '' && inputs.dry_run || 'false' }}
        # Check if this workflow was triggered from an organization account.
        is-org-account: ${{ github.event.organization && 'true' || 'false' }}
        log_level: ${{ inputs.log_level != '' && inputs.log_level || 'info' }}
        print_config: ${{ inputs.print_config != '' && inputs.print_config || 'false' }}
        renovate_git_author_email: ${{ format('{0}+{1}[bot]@users.noreply.github.com', inputs.renovate_app_id, inputs.renovate_app_slug) }}
        cache: ${{ inputs.cache == 'true' }}
        zzglobal_config: |-
          {
            allowedPostUpgradeCommands: [
              '^(npx )?corepack(?:@\\d+(?:\\.\\d+\\.\\d+)?)? enable$',
              '^npm ci( --force)?( --ignore-scripts)?$',
              '^npm install -g (npm|pnpm)(?:@\\d+(?:\\.\\d+\\.\\d+)?)?$',
              '^(npx|pnpm|yarn) prettier(?:@\\d+(?:\\.\\d+\\.\\d+)?)?( --no-color)? --write \\.$',
              '^(pnpm|yarn) install( --force)?( --frozen-lockfile)?( --ignore-scripts)?$',
              '^(npm|pnpm|yarn) run (bootstrap|build(-release)?|fix|format|update-snapshots)$',
              '^yarn install( --force)?( --immutable)?( --immutable-cache)?$',
              '^(?:\\[ -w \\.npmrc \\] && )?git checkout -- \\.npmrc(?: \\|\\| true)?$',
            ],
            description: [
              'Use the global config preset for the @bfra-me organization.',
              '_See the [self-hosted Renovate action](https://github.com/bfra-me/renovate-action/blob/main/action.yaml) for details._',
            ],
            onboardingConfig: {
              '$schema': 'https://docs.renovatebot.com/renovate-schema.json',
              extends: ['github>bfra-me/renovate-config'],
            },
            onboardingConfigFileName: '.github/renovate.json5',
            onboardingPrTitle: 'feat(deps): configure Renovate',
            onboardingRebaseCheckbox: true,
          }
      run: |
        # Create outputs for this configuration
        sed 's/^[[:space:]]*//' <<EOF >> $GITHUB_OUTPUT
          autodiscover=${{ env.autodiscover }}
          base-branches=${{ inputs.branch && format('["{0}"]', inputs.branch) || '' }}
          cache-dir=${RENOVATE_CACHE_DIR:-/tmp/renovate/cache}
          cache-key=renovate-cache-v$(echo ${{ env.RENOVATE_VERSION }} | cut -d. -f1)
          docker-image=ghcr.io/renovatebot/renovate:${{ env.RENOVATE_VERSION }}
          dry-run=${{ env.dry_run }}
          enable-cache=${{ env.cache }}
          global-config=$(echo "${zzglobal_config}" | tr -d '\n')
          is-org-account=${{ env.is-org-account }}
          log-level=${{ env.log_level }}
          print-config=${{ env.print_config }}
          renovate-git-author-email=${{ env.renovate_git_author_email }}
          renovate-git-author=${{ format('{0}[bot] <{1}>', inputs.renovate_app_slug, env.renovate_git_author_email) }}
          renovate-username=${{ format('{0}[bot]', inputs.renovate_app_slug) }}
          renovate-version=${{ env.RENOVATE_VERSION }}
        EOF
      shell: 'bash -Eeuo pipefail {0}'

    - name: Get Workflow Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@dc0413987a085fa17d19df9e47d4677cf81ffef3 # v3.0.0
      with:
        application_id: ${{ inputs.renovate_app_id }}
        application_private_key: ${{ inputs.renovate_app_pem }}
        organization: ${{ fromJSON(steps.configure.outputs.is-org-account) && github.repository_owner || '' }}
        permissions: >
          actions:write,
          checks:write,
          contents:write,
          issues:write,
          members:read,
          metadata:read,
          pull_requests:write,
          statuses:write,
          vulnerability_alerts:read,
          workflows:write

    - name: Restore Renovate Cache
      id: renovate-cache
      if: steps.configure.outputs.enable-cache == 'true'
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        enableCrossOsArchive: true
        key: ${{ steps.configure.outputs.cache-key }}
        path: ${{ steps.configure.outputs.cache-dir }}

    - name: Prepare Renovate Cache
      if: steps.configure.outputs.enable-cache == 'true'
      run: |
        [ -d /tmp/renovate ] && sudo chown -R runneradmin:root /tmp/renovate || true
      shell: 'bash -Eeuo pipefail {0}'

    - name: Renovate ${{ steps.configure.outputs.renovate-version }}
      uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
      env:
        FORCE_COLOR: '3'
        LOG_LEVEL: ${{ steps.configure.outputs.log-level }}
        RENOVATE_AUTODISCOVER: 'true'
        RENOVATE_AUTODISCOVER_FILTER: ${{ steps.configure.outputs.autodiscover == 'false' && github.repository || '' }}
        RENOVATE_BASE_BRANCHES: ${{ steps.configure.outputs.base-branches }}
        RENOVATE_USE_BASE_BRANCH_CONFIG: ${{ steps.configure.outputs.base-branches && 'merge' || 'none' }}
        RENOVATE_BRANCH_PREFIX_OLD: 'renovate-github/'
        RENOVATE_CACHE_DIR: ${{ steps.configure.outputs.cache-dir }}
        RENOVATE_CACHE_NPM_MINUTES: '60'
        RENOVATE_CONFIG: ${{ steps.configure.outputs.global-config }}
        RENOVATE_DEPENDENCY_DASHBOARD_FOOTER: '\n- [ ] <!-- manual job -->Check here to trigger a Renovate run on this repository\n'
        RENOVATE_DRY_RUN: ${{ fromJSON(steps.configure.outputs.dry-run) && 'full' || '' }}
        RENOVATE_GIT_AUTHOR: ${{ steps.configure.outputs.renovate-git-author }}
        RENOVATE_GIT_IGNORED_AUTHORS: |-
          [
            "bot@renovateapp.com",
            "29139614+renovate[bot]@users.noreply.github.com",
            "support@github.com",
            "261136+bfra-me@users.noreply.github.com",
            "118100583+bfra-me[bot]@users.noreply.github.com",
            "137683033+mrbro-bot[bot]@users.noreply.github.com",
            "109017866+fro-bot[bot]@users.noreply.github.com",
            "${{ steps.configure.outputs.renovate-git-author-email }}"
          ]
        RENOVATE_HOST_RULES: |-
          [
            {
              "abortIgnoreStatusCodes": [404],
              "abortOnError": true,
              "dnsCache": true
            }
          ]
        RENOVATE_PLATFORM: github
        RENOVATE_PLATFORM_COMMIT: 'true'
        RENOVATE_PRESET_CACHE_PERSISTENCE: ${{ steps.configure.outputs.enable-cache == 'true' }}
        RENOVATE_PRINT_CONFIG: ${{ steps.configure.outputs.print-config }}
        RENOVATE_REPOSITORY_CACHE: ${{ steps.configure.outputs.enable-cache == 'true' && 'enabled' || 'disabled' }}
        RENOVATE_USERNAME: ${{ steps.configure.outputs.renovate-username }}
      with:
        env-regex: '^(?:CI|FORCE_COLOR|GITHUB_(?:(?!PATH|ENV).)+|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy|LOG_LEVEL|NODE_OPTIONS|RENOVATE_\w+|RUNNER_\w+)$'
        docker-cmd-file: '${{ github.action_path }}/docker/entrypoint.sh'
        docker-user: root
        mount-docker-socket: true
        renovate-version: ${{ steps.configure.outputs.renovate-version }}
        token: ${{ steps.get_workflow_token.outputs.token }}

    - name: Finalize Renovate Cache
      if: |
        (success() || failure()) &&
        steps.configure.outputs.enable-cache == 'true' &&
        steps.renovate-cache.outputs.cache-hit != 'true' || github.event_name == 'push'
      env:
        GH_REPO: ${{ github.event.repository.full_name }}
        GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      run: |
        [ -d /tmp/renovate ] && sudo chown -R $(whoami) /tmp/renovate
        gh api -X DELETE /repos/{owner}/{repo}/actions/caches?key=${{ steps.configure.outputs.cache-key }} ||
          echo "Could not delete cache for $GH_REPO"
      shell: 'bash -Eeuo pipefail {0}'

    - name: Save Renovate cache
      if: |
        (success() || failure()) &&
        steps.configure.outputs.enable-cache == 'true' &&
        steps.renovate-cache.outputs.cache-hit != 'true' || github.event_name == 'push'
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        enableCrossOsArchive: true
        key: ${{ steps.configure.outputs.cache-key }}
        path: ${{ steps.configure.outputs.cache-dir }}
  using: composite
