---
name: Renovate Action
description: Self-hosted Renovate GitHub Action
author: bfra.me

inputs:
  autodiscover:
    description: Autodiscover all repositories.
    required: false
    default: 'false'
  branch:
    description: Run Renovate on this branch.
    required: false
  cache:
    description: Enable the Renovate cache.
    required: false
    default: 'true'
  dry_run:
    description: Perform a dry run by logging messages instead of creating/updating/deleting branches and PRs.
    required: false
    default: 'false'
  log_level:
    description: Set the log level.
    required: false
    default: 'debug'
  print_config:
    description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
    required: false
    default: 'false'
  renovate_app_id:
    description: The ID of the GitHub App that will be used to run Renovate.
    required: true
  renovate_app_pem:
    description: The private key of the GitHub App that will be used to run Renovate.
    required: true
  renovate_app_slug:
    description: The slug of the GitHub app to use for authentication.
    required: true

outputs:
  docker-image:
    description: The name of the Renovate Docker image
    value: ${{ steps.configure.outputs.docker-image }}
  renovate-version:
    description: The Renovate version
    value: ${{ steps.configure.outputs.renovate-version }}

runs:
  steps:
    - name: Configure
      id: configure
      env:
        RENOVATE_VERSION: 37.140.10 # renovate: datasource=docker depName=renovate packageName=ghcr.io/renovatebot/renovate
        autodiscover: ${{ inputs.autodiscover != '' && inputs.autodiscover || 'false' }}
        dry_run: ${{ inputs.dry_run != '' && inputs.dry_run || 'false' }}
        # Check if this workflow was triggered from an organization account.
        is-org-account: ${{ github.event.organization && 'true' || 'false' }}
        log_level: ${{ inputs.log_level != '' && inputs.log_level || 'debug' }}
        print_config: ${{ inputs.print_config != '' && inputs.print_config || 'false' }}
        renovate_git_author_email: ${{ format('{0}+{1}[bot]@users.noreply.github.com', inputs.renovate_app_id, inputs.renovate_app_slug) }}
        cache: ${{ inputs.cache == 'true' }}
        zzglobal_config: |-
          {
            allowedPostUpgradeCommands: [
              '^(npx )?corepack(?:@\\d+(?:\\.\\d+\\.\\d+)?)? enable$',
              '^npm ci( --ignore-scripts)?$',
              '^npm install -g (npm|pnpm)(?:@\\d+(?:\\.\\d+\\.\\d+)?)?$',
              '^(npx|pnpm|yarn) prettier(?:@\\d+(?:\\.\\d+\\.\\d+)?)?( --no-color)? --write \\.$',
              '^(pnpm|yarn) install( --frozen-lockfile)?( --ignore-scripts)?$',
              '^(pnpm|yarn) run (build|fix|format)$',
              '^yarn install( --immutable)?( --immutable-cache)?$',
              '^git checkout -- .npmrc$',
            ],
            description: [
              'Use the global config preset for the @bfra-me organization.',
              '_See the [self-hosted Renovate action](https://github.com/bfra-me/renovate-action/blob/main/action.yaml) for details._',
            ],
            onboardingConfig: {
              '$schema': 'https://docs.renovatebot.com/renovate-schema.json',
              extends: ['github>bfra-me/renovate-config#v2.3.7'],
            },
            onboardingConfigFileName: '.github/renovate.json5',
            onboardingPrTitle: 'feat(deps): configure Renovate',
            onboardingRebaseCheckbox: true,
            packageRules: [
              {
                matchPackagePatterns: ['*'],
                rangeStrategy: 'pin',
              },
              {
                matchDepTypes: ['engines', 'peerDependencies'],
                rangeStrategy: 'update-lockfile',
              },
            ],
          }

      # Use the contains function to convert the boolean input to a string and compare it to 'false'. This is
      # required when the workflow is triggered from workflow_call because the github context is that of the workflow
      # that called this workflow.
      run: |
        # Create outputs for this configuration
        sed 's/^[[:space:]]*//' <<EOF >> $GITHUB_OUTPUT
          autodiscover=${{ env.autodiscover }}
          base-branches=${{ inputs.branch && format('["{0}"]', inputs.branch) || '' }}
          docker-image=ghcr.io/renovatebot/renovate:${{ env.RENOVATE_VERSION }}
          dry-run=${{ env.dry_run }}
          enable-cache=${{ env.cache }}
          global-config=$(echo "${zzglobal_config}" | tr -d '\n')
          is-org-account=${{ env.is-org-account }}
          log-level=${{ env.log_level }}
          print-config=${{ env.print_config }}
          renovate-git-author-email=${{ env.renovate_git_author_email }}
          renovate-git-author=${{ format('{0}[bot] <{1}>', inputs.renovate_app_slug, env.renovate_git_author_email) }}
          renovate-username=${{ format('{0}[bot]', inputs.renovate_app_slug) }}
          renovate-version=$(echo "${{ env.RENOVATE_VERSION }}")
          repositories=${{ !fromJSON(env.autodiscover) && format('["{0}"]', github.repository) || '' }}
        EOF
      shell: 'bash -Eeuo pipefail {0}'

    - name: Get Workflow Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
      with:
        application_id: ${{ inputs.renovate_app_id }}
        application_private_key: ${{ inputs.renovate_app_pem }}
        organization: ${{ fromJSON(steps.configure.outputs.is-org-account) && github.repository_owner || '' }}
        permissions: >
          checks:write,
          contents:write,
          issues:write,
          members:read,
          metadata:read,
          pull_requests:write,
          statuses:write,
          vulnerability_alerts:read,
          workflows:write

    - name: Configure Renovate cache
      if: steps.configure.outputs.enable-cache == 'true'
      run: |
        echo "RENOVATE_CACHE_DIR=${RENOVATE_CACHE_DIR:-/tmp/renovate/cache}" >> $GITHUB_ENV
      shell: 'bash -Eeuo pipefail {0}'
    - id: renovate-cache
      name: Cache Renovate
      if: steps.configure.outputs.enable-cache == 'true'
      env:
        RENOVATE_CACHE_DIR: ${{ env.RENOVATE_CACHE_DIR }}
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        enableCrossOsArchive: true
        path: ${{ env.RENOVATE_CACHE_DIR }}
        key: >-
          ${{ github.repository_owner }}-renovate-cache-${{ steps.configure.outputs.renovate-version }}-${{ github.sha }}

    - name: Workaround Renovate cache permissions
      if: steps.configure.outputs.enable-cache == 'true'
      continue-on-error: true
      run: >
        [ -d /tmp/renovate ] && sudo chown -R 1000 /tmp/renovate || true
      shell: 'bash -Eeuo pipefail {0}'

    - name: Renovate ${{ steps.configure.outputs.renovate-version }}
      uses: renovatebot/github-action@f9c81dddc9b589e4e6ae0326d1e36f6bc415d230 # v39.2.4
      env:
        FORCE_COLOR: '3'
        LOG_LEVEL: ${{ steps.configure.outputs.log-level }}
        RENOVATE_AUTODISCOVER: ${{ steps.configure.outputs.autodiscover }}
        RENOVATE_BASE_BRANCHES: ${{ steps.configure.outputs.base-branches }}
        RENOVATE_USE_BASE_BRANCH_CONFIG: ${{ steps.configure.outputs.base-branches && 'merge' || 'none' }}
        RENOVATE_BRANCH_PREFIX_OLD: 'renovate-github/'
        RENOVATE_CACHE_NPM_MINUTES: '30'
        RENOVATE_CONFIG: ${{ steps.configure.outputs.global-config }}
        RENOVATE_DEPENDENCY_DASHBOARD_FOOTER: '\n- [ ] <!-- manual job -->Check here to trigger a Renovate run on this repository\n'
        RENOVATE_DRY_RUN: ${{ fromJSON(steps.configure.outputs.dry-run) && 'extract' || '' }}
        RENOVATE_GIT_AUTHOR: ${{ steps.configure.outputs.renovate-git-author }}
        RENOVATE_GIT_IGNORED_AUTHORS: |-
          [
            "bot@renovateapp.com",
            "29139614+renovate[bot]@users.noreply.github.com",
            "support@github.com",
            "261136+bfra-me@users.noreply.github.com",
            "118100583+bfra-me[bot]@users.noreply.github.com",
            "137683033+mrbro-bot[bot]@users.noreply.github.com",
            "109017866+fro-bot[bot]@users.noreply.github.com",
            "${{ steps.configure.outputs.renovate-git-author-email }}"
          ]
        RENOVATE_HOST_RULES: |-
          [
            {
              "abortIgnoreStatusCodes": [404],
              "abortOnError": true,
              "dnsCache": true
            }
          ]
        RENOVATE_MIGRATE_PRESETS: |-
          {
            'github>bfra-me/renovate-config:automerge/enabled': 'github>bfra-me/renovate-config:automerge/_enable'
          }
        RENOVATE_PLATFORM: github
        RENOVATE_PLATFORM_COMMIT: 'true'
        RENOVATE_PRESET_CACHE_PERSISTENCE: ${{ steps.configure.outputs.enable-cache == 'true' }}
        RENOVATE_PRINT_CONFIG: ${{ steps.configure.outputs.print-config }}
        RENOVATE_REPOSITORIES: ${{ steps.configure.outputs.repositories }}
        RENOVATE_REPOSITORY_CACHE: ${{ steps.configure.outputs.enable-cache == 'true' && 'enabled' || 'disabled' }}
        RENOVATE_USERNAME: ${{ steps.configure.outputs.renovate-username }}
      with:
        env-regex: '^(?:CI|FORCE_COLOR|GITHUB_(?:(?!PATH|ENV).)+|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy|LOG_LEVEL|NODE_OPTIONS|RENOVATE_\w+|RUNNER_\w+)$'
        mount-docker-socket: true
        renovate-version: ${{ steps.configure.outputs.renovate-version }}
        token: 'x-access-token:${{ steps.get_workflow_token.outputs.token }}'

    - name: Restore Renovate cache permissions
      if: always() && steps.configure.outputs.enable-cache == 'true'
      continue-on-error: true
      run: >
        [ -d /tmp/renovate ] && sudo chown -R $(whoami) /tmp/renovate
      shell: 'bash -Eeuo pipefail {0}'
  using: composite
