name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.event.number || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: true
  LOG_LEVEL: debug

jobs:
  validate-config-presets:
    name: Validate config presets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - default
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Validating ${{ env.RENOVATE_CONFIG_FILE }}
        run: npx -p renovate renovate-config-validator

  renovate-pr:
    if: contains(github.event_name, 'pull_request')
    name: Renovate PR
    needs: validate-config-presets
    secrets: inherit
    uses: ./.github/workflows/renovate.yaml
    with:
      autodiscover: false
      branch: ${{ github.head_ref }}
      dry_run: true
      print_config: true
