name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        default: true
        required: false
        type: boolean

concurrency:
  group: '${{ github.workflow }}-${{ github.event.number || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: true
  LOG_LEVEL: debug

jobs:
  validate-config-presets:
    name: Validate config presets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - default
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Validating ${{ env.RENOVATE_CONFIG_FILE }}
        run: npx -p renovate renovate-config-validator

  # Renovate PRs and pushes to main.
  renovate-ci:
    if: github.repository == 'bfra-me/renovate-config'
    name: Renovate CI
    needs: validate-config-presets
    secrets: inherit
    uses: ./.github/workflows/renovate.yaml
    with:
      autodiscover: false
      branch: ${{ github.head_ref }}
      dry_run: ${{ github.event_name == 'pull_request' && true }}
      print_config: ${{ github.event_name == 'pull_request' && true }}

  release:
    env:
      DRY_RUN: true
    name: Release
    needs: renovate-ci
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Access Token
        id: get-workflow-access-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
          token: ${{ steps.get-workflow-access-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '18.x'

      - name: Get Release Options
        env:
          INPUT_DRY_RUN: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.dry_run && 'true' || 'false' }}
          IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: |
          if [[ $INPUT_DRY_RUN != 'true' || $IS_DEFAULT_BRANCH == 'true'  ]]; then
            echo "DRY_RUN=false" >> $GITHUB_ENV
          fi

      - name: Semantic Release
        env:
          GIT_AUTHOR_EMAIL: '118100583+bfra-me[bot]@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'bfra.me'
          GIT_COMMITTER_EMAIL: '118100583+bfra-me[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'bfra.me'
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
        run: |
          # Run `semantic-release`
          npm install conventional-changelog-conventionalcommits@6.1.0
          npx semantic-release@21.1.1 --dry-run ${{ env.DRY_RUN }}
