name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.event.number || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: true
  LOG_LEVEL: debug

jobs:
  validate-config-presets:
    name: Validate config presets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - default
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Validating ${{ env.RENOVATE_CONFIG_FILE }}
        run: npx -p renovate renovate-config-validator

  renovate-ci:
    # Renovate PRs (as a dry run) and pushes to main.
    if: >
      github.repository == 'bfra-me/renovate-config' &&
      (
        contains(github.event_name, 'pull_request') ||
        github.ref == 'refs/heads/main'
      )
    name: Renovate CI
    needs: validate-config-presets
    secrets: inherit
    uses: ./.github/workflows/renovate.yaml
    with:
      autodiscover: false
      branch: ${{ github.head_ref }}
      dry_run: ${{ github.event_name == 'pull_request' && true }}
      print_config: ${{ github.event_name == 'pull_request' && true }}
