packages:
  - docs

overrides:
  esbuild@>=0.17.0 <0.28.1: '>=0.28.1'
  undici@>=6.0.0 <6.27.0: 6.27.0
  undici@>=7.0.0 <7.24.0: 7.28.0
  smol-toml: 1.7.0
  fast-uri: 3.1.2

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
