packages:
  - docs

overrides:
  undici@>=7.0.0 <7.24.0: 7.24.7
  smol-toml: 1.6.1

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
