packages:
  - docs
  - packages/*

overrides:
  undici@>=7.0.0 <7.24.0: 7.24.3

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
