packages:
  - docs
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
