---
name: Release

'on':
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        default: true
        required: false
        type: boolean
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

jobs:
  release:
    env:
      DRY_RUN: true
      FORCE_COLOR: 3
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Access Token
        id: get-workflow-access-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          token: ${{ steps.get-workflow-access-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: '18.x'

      - name: Get Release Options
        env:
          INPUT_DRY_RUN: ${{ github.event.inputs.dry_run && 'true' || 'false' }}
          IS_DEFAULT_BRANCH: ${{ github.ref == 'refs/heads/${{ github.event.repository.default_branch }}' }}
        run: |
          if [[ $INPUT_DRY_RUN != 'true' || $IS_DEFAULT_BRANCH == 'true'  ]]; then
            echo "DRY_RUN=false" >> $GITHUB_ENV
          fi

      - name: Semantic Release
        env:
          GIT_AUTHOR_EMAIL: '118100583+bfra-me[bot]@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'bfra.me'
          GIT_COMMITTER_EMAIL: '118100583+bfra-me[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'bfra.me'
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
        run: |
          # Run `semantic-release`
          npm install conventional-changelog-conventionalcommits
          npx semantic-release@21.0.7 --dry-run ${{ env.DRY_RUN }}
