---
name: Renovate

on:
  push:
    branches: [main]
    paths:
      - '*.json'
      - '.github/renovate.json'
      - '.github/workflows/renovate.yaml'
  schedule:
    - cron: '0/15 * * * *'
  workflow_call:
    inputs:
      autodiscover:
        description: Autodiscover all repositories.
        required: false
        type: boolean
        default: true
      dry_run:
        description: Perform a dry run by logging messages instead of creating/updating/deleting branches and PRs.
        required: false
        type: boolean
        default: true
      log_level:
        description: Set the log level.
        required: false
        type: string
        default: 'debug'
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
    secrets:
      APPLICATION_ID:
        description: GitHub App ID
        required: true
      APPLICATION_PRIVATE_KEY:
        description: GitHub App private key
        required: true
  workflow_dispatch:
    inputs:
      autodiscover:
        description: Autodiscover all repositories.
        required: false
        type: boolean
        default: true
      dry_run:
        description: Perform a dry run by logging messages instead of creating/updating/deleting branches and PRs.
        required: false
        type: boolean
        default: true
      log_level:
        description: Set the log level.
        required: false
        type: choice
        default: 'debug'
        options: ['trace', 'debug', 'info', 'warn', 'error', 'fatal']
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

concurrency:
  group: '${{ github.repository }}-${{ github.workflow }}-$${{ github.ref }}'
  cancel-in-progress: false

permissions: {}

env:
  # Use the contains function to convert the boolean input to a string and compare it to 'false'. This is required when
  # the workflow is triggered from workflow_call because the github context is that of the workflow that called this
  # workflow.
  AUTODISCOVER: ${{ inputs.autodiscover || contains(inputs.autodiscover, 'false') && 'false' || 'true' }}
  DRY_RUN: ${{ inputs.dry_run || contains(inputs.dry_run, 'false') && 'false' }}
  FORCE_COLOR: 3

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
          permissions: >
            checks:write,
            contents:write,
            issues:write,
            pull_requests:write,
            vulnerability_alerts:read,
            workflows:write

      - name: Renovate
        uses: renovatebot/github-action@2529763aa12e6d5b445bc911e8bd8cce2a4f205c # v36.0.1
        with:
          env-regex: '^(?:RENOVATE_\w+|FORCE_COLOR|GITHUB_COM_TOKEN|LOG_LEVEL|NODE_OPTIONS)$'
          renovate-version: ${{ env.RENOVATE_VERSION }}
          token: 'x-access-token:${{ steps.get_workflow_token.outputs.token }}'
        env:
          LOG_LEVEL: ${{ inputs.log_level || 'debug' }}
          RENOVATE_AUTODISCOVER: ${{ env.AUTODISCOVER }}
          RENOVATE_CONFIG: '{
              "description": [
                "Use the global config preset for the @bfra-me organization.",
                "_See the [renovate workflow](https://github.com/bfra-me/renovate-config/blob/main/.github/workflows/renovate.yaml) for details._"
              ],
              "packageRules": [
                {
                  "matchPackagePatterns": ["*"],
                  "rangeStrategy": "pin"
                },
                {
                  "matchDepTypes": ["engines", "peerDependencies"],
                  "rangeStrategy": "update-lockfile"
                }
              ],
              "schedule": ["at any time"]
            }'
          RENOVATE_DRY_RUN: ${{ fromJSON(env.DRY_RUN) && 'full' || '' }}
          RENOVATE_GIT_AUTHOR: 'bfra-me[bot] <118100583+bfra-me[bot]@users.noreply.github.com>'
          RENOVATE_GIT_IGNORED_AUTHORS: '["bot@renovateapp.com","29139614+renovate[bot]@users.noreply.github.com","support@github.com","261136+bfra-me@users.noreply.github.com"]'
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_PRINT_CONFIG: ${{ inputs.print_config || 'false' }}
          RENOVATE_REPOSITORIES: ${{ !fromJSON(env.AUTODISCOVER) && format('["{0}"]', github.repository) || '' }}
          RENOVATE_USERNAME: 'bfra-me[bot]'
          RENOVATE_VERSION: 35.15.0 # renovate: datasource=docker depName=renovate packageName=renovate/renovate
