---
name: Renovate (Development)

on:
  push:
    branches:
      - main
      - develop
      - 'renovate/**'
      - 'feature/**'
  pull_request:
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level for debugging
        required: false
        default: debug
        type: choice
        options:
          - silent
          - error
          - warn
          - info
          - debug
          - trace
      dry-run:
        description: Run in dry-run mode
        required: false
        default: true
        type: boolean
  schedule:
    - cron: '0 */2 * * 1-5'

jobs:
  renovate:
    name: Renovate (Development)
    runs-on: ubuntu-latest
    steps:
      - uses: bfra-me/renovate-action@v9
        with:
          dry-run: ${{ github.event.inputs.dry-run == 'true' || github.event_name == 'pull_request' }}
          log-level: ${{ github.event.inputs.log-level || 'debug' }}
          renovate-app-id: ${{ secrets.APPLICATION_ID }}
          renovate-app-private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          print-config: true
          cache: false
