---
name: Renovate (Organization Setup)

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: bfra-me/renovate-action@v9
        with:
          dry-run: ${{ github.event_name == 'pull_request' }}
          renovate-app-id: ${{ secrets.APPLICATION_ID }}
          renovate-app-private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          autodiscover: true
          autodiscover-filter: '["org/repo1", "org/repo2", "org/important-*"]'
          cache: true
