---
name: Renovate (Templates Disabled)

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: bfra-me/renovate-action@v7
        with:
          dry-run: ${{ github.event_name == 'pull_request' }}
          renovate-app-id: ${{ secrets.APPLICATION_ID }}
          renovate-app-private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          # Disable custom templates to use Renovate's default PR and issue format
          enable-custom-templates: false
