---
name: Renovate Cache Testing

'on':
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

concurrency:
  # Ue the same concurrency group as the renovate workflow
  group: '${{ github.repository }}-renovate-$${{ github.ref }}'
  cancel-in-progress: false

env:
  RENOVATE_REPOSITORY_CACHE: enabled

jobs:
  explore-renovate-cache:
    name: Explore Renovate Cache
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -alhFR /tmp || exit 0

  renovate-and-cache:
    needs: explore-renovate-cache
    secrets: inherit
    uses: ./.github/workflows/renovate.yaml
    with:
      autodiscover: false
      dry_run: false
      print_config: ${{ inputs.print_config }}

  post-renovate-cache:
    needs: renovate-and-cache
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -alhFR /tmp || exit 0
